### PR TITLE
Add my user profile to the python-namibia website

### PR DESCRIPTION
**Pull request by Namibnat**

### CODE REVIEW

**Comment by jasonrudolph** [comment]
Thanks for the contribution. I think it's *almost* ready to merge. We just need to make the file name match your username. The file is currently `vernonswanepoel.yml`, but it needs to be `Namibnat.yml`.

Can you make that change? If you need any help, just let us know.

**Comment by Robertt1** [comment]
add me Robert

**Comment by shayfrendt** [comment]
Awesome!

**Comment by jasonrudolph** [comment]
> add me Robert

@Robertt1: We'll happily add you. You'll just need to open a pull request. I see that you've already forked the project (https://github.com/Robertt1/python-namibia.github.io). Can you create a pull request that adds a file with your info? If you need any help, please ask and we'll be happy to offer assistance.

**Comment by jasonrudolph** [comment]
Thanks for this contribution! :star2: You should see your entry on http://python-namibia.github.io/ in the next few minutes.

We hope you enjoy your journey with Git and GitHub. As you get ready to take the next steps, we recommend:

- Reading [The Git Parable](http://tom.preston-werner.com/2009/05/19/the-git-parable.html) to understand the concepts that make Git powerful.
- Enjoying our videos on the [GitHub Training YouTube channel](https://www.youtube.com/user/GitHubGuides), including [The Basics of Git and GitHub](https://www.youtube.com/watch?v=u6G3fbmpWr8&feature=youtu.be) and [Collaboration with Git and GitHub](https://www.youtube.com/watch?v=SCZF6I-Rc4I&feature=c4-overview-vl&list=PLg7s6cbtAD15Das5LK9mXt_g59DLWxKUe).
- Browsing our [handy guides](https://guides.github.com/), including a detailed walkthrough that will help you [get your project on GitHub](https://guides.github.com/introduction/getting-your-project-on-github/).
- Bookmarking the free [Pro Git ebook](http://git-scm.com/book) and refering to it any time you want to understand a specific Git concept or command.
- Exploring some of the excellent [open source projects under development in Africa](https://github.com/showcases/made-in-africa).

Happy collaborating! :heart::octocat:

**Pull request merged**
