### PR TITLE
Create aaronjeke.yml

### PR DESCRIPTION
**Pull request by aaronjeke**

### CODE REVIEW

**Comment by aaronjeke** [comment]
Smiles

**Comment by jasonrudolph** [comment]
@aaronjeke: This pull request looks good. Did you mean to close it?

**Comment by aaronjeke** [comment]
Ooops yeah...

**Comment by jasonrudolph** [comment]
@aaronjeke: If you'd still like us to merge this pull request, please reopen it, and we'll get it merged for you.

**Comment by aaronjeke** [comment]
How do I open it?

On 14 February 2015 at 09:32, Jason Rudolph <notifications@github.com>
wrote:

> @aaronjeke <https://github.com/aaronjeke>: If you'd still like us to
> merge this pull request, please reopen it, and we'll get it merged for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python-namibia/python-namibia.github.io/pull/18#issuecomment-74367062>
> .
>



-- 
Dalitso Jeke. A

Tel(MTC Namibia): +264818003423
Alternat email:   dalitsojeke@yahoo.com

**Comment by aaronjeke** [comment]
I managed to open it...

**Comment by jasonrudolph** [comment]
Thanks for this contribution! :star2: You should now see your entry on http://python-namibia.github.io/.

We hope you enjoy your journey with Git and GitHub. As you get ready to take the next steps, we recommend:

- Reading [The Git Parable](http://tom.preston-werner.com/2009/05/19/the-git-parable.html) to understand the concepts that make Git powerful.
- Enjoying our videos on the [GitHub Training YouTube channel](https://www.youtube.com/user/GitHubGuides), including [The Basics of Git and GitHub](https://www.youtube.com/watch?v=u6G3fbmpWr8&feature=youtu.be) and [Collaboration with Git and GitHub](https://www.youtube.com/watch?v=SCZF6I-Rc4I&feature=c4-overview-vl&list=PLg7s6cbtAD15Das5LK9mXt_g59DLWxKUe).
- Browsing our [handy guides](https://guides.github.com/), including a detailed walkthrough that will help you [get your project on GitHub](https://guides.github.com/introduction/getting-your-project-on-github/).
- Bookmarking the free [Pro Git ebook](http://git-scm.com/book) and refering to it any time you want to understand a specific Git concept or command.
- Exploring some of the excellent [open source projects under development in Africa](https://github.com/showcases/made-in-africa).

Happy collaborating! :heart::octocat:

**Pull request merged**
